name: 自动更新GitHub贪吃蛇动画

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  snake-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 生成贪吃蛇SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/snake-animation.svg

      - name: 推送图片到独立分支
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: snake-res
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
